version: "2"
services:
  app:
    build: ./ml-items-challenge
    restart: always
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.23
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: challengeml
      MYSQL_PASSWORD: 1challengeml
      MYSQL_DATABASE: meli
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro